apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: immichdb
spec:
  postgresVersion: 17
  users:
    - name:  baudolino
      databases:
        - immichbasedb
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteMany"
        resources:
          requests:
            storage: 5Gi
  backups:
    pgbackrest:
      repos:
      - name: repo2
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteMany"
            resources:
              requests:
                storage: 5Gi
