apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: immichdb
  namespace: postgres-operator
spec:
  postgresVersion: 17
  users:
    - name:  baudolino
      databases:
        - immichbasedb
  instances:
    - name: instance2
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteMany"
        resources:
          requests:
            storage: 5Gi
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          #shared_preload_libraries: "timescaledb"
          ssl: "off"
          password_encryption: "md5"
        pg_hba:
          - "hostnossl all all all md5"
  backups:
    pgbackrest:
      repos:
      - name: repo2
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteMany"
            resources:
              requests:
                storage: 5Gi
